export const APPLICATION_CONFIG = {
    LATTICE_URL: import.meta.env.VITE_LATTICE_URL,
    ENVIRONMENT_TOKEN: import.meta.env.VITE_ENVIRONMENT_TOKEN,
    SANDBOX_TOKEN: import.meta.env.VITE_SANDBOX_TOKEN
}